export const builds = [
    { id: 1, role:"DPS", dmgType: "Power", boon: "none",  class:"Elementalist", spec:"Catalyst", recExpansions:["EoD", "SotO"],
        notes: ["You need at least 57% base crit chance (you will get +25% from fury, and about 18% from Elemental Empowerment+Empowered Empowerment)"],
        exoticGearLink:"http://gw2skills.net/editor/?PGgEwEW2AblRxuYk4or8FNB-DSIUR0wfIchrVCUhCQm3CohCzAAA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PGgEwEW2AblRxuYk4or8FNB-DSIYR0wfG1KBqQBIzbB0QhZAAA-e",
        buildTemplate:"[&DQYfHSkfQyYnDwAA+BoAAL4BAADLAAAAJgAAAAAAAAAAAAAAAAAAAAAAAAA=]",
        primaryWeapons:["Sword", "Warhorn"],
        secondaryWeapons:[],
        runes:"Dragonhunter",
        sigils:["Force", "Impact"],
        relic:"Fireworks",
        dpsReportLink:"",
        instructions:["Use All Weapon Skills off Cooldown", 
            "Switch between Fire and Air Regularly", 
            "Use your Jade Sphere as soon as you enter a new element.", 
            "Use [Relentless Fire] when you enter Fire attunement.", 
            "Use [Glyph of Storms] when you enter Air attunement."]
    }, 
    { id: 2, role:"DPS", dmgType: "Power", boon: "none",  class:"Elementalist", spec:"Weaver", recExpansions:["PoF", "SotO"],
        notes: ["You need at least 60% base crit chance (you will get +25% crit chance from fury, and +15% from Superior Elements)",
            "This build is a simplified version of Power Weaver, but Weaver is still a very fast class. Don’t be discouraged if you struggle with it at first."
        ],
        exoticGearLink:"http://gw2skills.net/editor/?PGgEwEWmB7gJxoYk4or89yA-DyQUhohqfHSxhwFuWJQFKAZeLgGKMDAA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PGgEwEWmB7gJxoYk4or89yA-DSIYR0wfG1KBqQBIzbB0QhZAAA-e",
        buildTemplate:"[&DQYfHSkfOBl0AAAAUAEAADUXAAC+AQAAJgAAAAAAAAAAAAAAAAAAAAAAAAA=]",
        primaryWeapons:["Sword", "Warhorn"],
        secondaryWeapons:[],
        runes:"Dragonhunter",
        sigils:["Force", "Impact"],
        relic:"Fireworks",
        dpsReportLink:"",
        instructions:["Flip Attunements off cooldown. Air Twice, Fire Twice and repeat.", 
            "Only use Glyph of storms when it is attuned to air.",
            "When attuned to Air as the main (air on the left side) only auto attack.",
            "When attuned to Fire as the main use all weapon skills and the utilities [Primordial Stance] and [Arcane Blast]"
        ]
}, 
    { id: 3, role:"DPS", dmgType: "Power", boon: "none",  class:"Engineer", spec:"Scrapper", recExpansions:["HoT"],
        notes: ["You need at least 45% base crit chance (you will get +25% from fury, +15% from High Caliber, +15% from Hematic Focus)",
            "If using the exotic gear set, use Force and Accuracy Sigils instead"
        ],
        exoticGearLink:"http://gw2skills.net/editor/?PeQAIlRw2YQsG2JOuLvteA-DSIURUwXGRkAVUA2eWgGKcGBqA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PeQAIlRw2YQsG2JOuLvteA-DSIYRUwXG1mAVUA2eWgGKcGBqA-e",
        buildTemplate:"[&DQMGNyYvKz3ZEtkSJgHMEq4SrhInEycTiQGDEgAAAAAAAAAAAAAAAAAAAAACMwBVAAA=]",
        primaryWeapons:["Hammer"],
        secondaryWeapons:[],
        runes:"Scholar",
        sigils:["Force", "Impact"],
        relic:"Thief",
        dpsReportLink:"",
        instructions:["Use 5 and 2 off-cooldown.  (Skip other Hammer skills as they are usually a DPS loss.)",
            "Use all toolbelt skills (F1-F5) off-cooldown.",
            "Use all utility skills, heal, and elite off-cooldown."
        ]
},
    { id: 4, role:"DPS", dmgType: "Power", boon: "none",  class:"Engineer", spec:"Holosmith", recExpansions:["PoF", "SotO"],
        notes: ["You need at least 45% base crit chance (you will get +25% from fury, +15% from High Caliber, +15% from Hematic Focus)"],
        exoticGearLink:"http://gw2skills.net/editor/?PeQAIlJw2YRsDGKOuLvvTA-DyQUhogsfHKRZUbCURBY7ZBaowZEoC-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PeQAIlJw2YRsDGKOuLvvTA-DSIYRUwXG1mAVUA2eWgGKcGBqA-e",
        buildTemplate:"[&DQMGNyYvOScqDwAAVxYAAKMAAADlFgAA8BUAAAAAAAAAAAAAAAAAAAAAAAACMwBVAAA=]",
        primaryWeapons:["Hammer"],
        secondaryWeapons:[],
        runes:"Scholar",
        sigils:["Force", "Impact"],
        relic:"Thief",
        dpsReportLink:"https://dps.report/GPfQ-20240316-130609_golem",
        instructions:["Enter Photon Forge (F5) off-cooldown and be sure to reactivate to leave Forge before the heat bar fills completely (DO NOT OVERHEAT!).",
            "In Photon Forge, use 3 and 4 off-cooldown until you leave.",
            "Use F3 and F4 off-cooldown (even while in Photon Forge).",
            "When your heat moves into the red (>= 80%) use F2, 8, and your elite skill.",
            "Outside of Photon Forge, use Hammer 2 and 5 off-cooldown.  (Skip other Hammer skills as they are usually a DPS loss.)"
        ]
},
    { id: 5, role:"DPS", dmgType: "Power", boon: "none",  class:"Engineer", spec:"Mechanist", recExpansions:["EoD", "SotO"],
        notes: ["You need at least 45% base crit chance (you will get +25% from fury, +15% from High Caliber, +15% from Hematic Focus)"],
        exoticGearLink:"http://gw2skills.net/editor/?PeQAIlxWwgrauZt3uWcqOuLvxOA-DSIURUwfIchrVCUhCQm3CohCzAAA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PeQAIlxWwgrauZt3uWcqOuLvxOA-DSIYRUwfG1KBqQBIzbB0QhZAAA-e",
        buildTemplate:"[&DQMmLwY3Rh0NGxQBDhsBARAbXwEaG14BCRsSAQAAAAAAAAAAAAAAAAAAAAADMwA1AFcAAA==]",
        primaryWeapons:["Hammer"],
        secondaryWeapons:[],
        runes:"Dragonhunter",
        sigils:["Force", "Impact"],
        relic:"Fireworks",
        dpsReportLink:"https://dps.report/DQtu-20240305-201401_golem",
        instructions:[
            "Use Hammer 5 and 2 off cooldown.",
            "Use [Overclock Signet] after using Hammer 5",
            "Use F1, F2, F3 skills shortly after using the Hammer 5"
        ]
},
    { id: 6, role:"DPS", dmgType: "Power", boon: "none",  class:"Guardian", spec:"Dragonhunter", recExpansions:["HoT"],
        notes: ["You need at least 40% base crit chance (you will get +25% from fury, +25% from resolution because of Righteous Instincts, +10% from Radiant Power)",
            "Do NOT spend resources to make exotic Dragon’s gear"
        ],
        exoticGearLink:"http://gw2skills.net/editor/?PWQAElFwcYIsJWJO0L+NdA-DSIURUwXIcx1mAVUA2+IgGKMDAA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PWQAElFwcYIsJWJO0L+NdA-DSRYBRBtG2cIqOLjaTgKKAbfEQDFmBAA-e",
        buildTemplate:"[&DQEQPio6GzoDAQAAihIAAEgBAAD+AAAAtRIAAAAAAAAAAAAAAAAAAAAAAAACMgAzAAA=]",
        primaryWeapons:["Greatsword"],
        secondaryWeapons:[],
        runes:"Dragonhunter",
        sigils:["Force", "Impact"],
        relic:"Fireworks",
        dpsReportLink:"",
        instructions:["Greatsword  4 > Greatsword 2 is big damage.  Always use these skills together and in this order.  Wait for both to be off-cooldown if necessary.",
            "Use [Procession of Blades], [Sword of Justice] and [Dragon's Maw] off cooldown.",
            "Using the first cast of GS5 and F1 will offer a damage multiplier to your skills. Only use the first cast."
        ]
},
    { id: 7, role:"DPS", dmgType: "Power", boon: "none",  class:"Mesmer", spec:"Chronomancer", recExpansions:["HoT", "SotO"],
        notes: ["Exotic gear is possible for this build, but not recommended because of the consequent damage loss."],
        exoticGearLink:"http://gw2skills.net/editor/?PigAgylVwYYLsNWJO0KdNfA-DyQUhoBNuDH3YEJBqUASPLwyomRAA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PigAgylVwYYLsNWJO0KdNfA-DyQYhohK6cHSPsxISCUpAkeWgGKcGBqA-e",
        buildTemplate:"[&DQcBHQoaKD4jDyMPBBNqAc8SawGPAY8BsxK8AQAAAAAAAAAAAAAAAAAAAAADLwBaAFcAAA==]",
        primaryWeapons:["Dagger", "Sword"],
        secondaryWeapons:[],
        runes:"Infiltration",
        sigils:["Force", "Accuracy"],
        relic:"Thief",
        dpsReportLink:"https://dps.report/5MoS-20240316-002720_golem",
        instructions:["5 > 9 > Reset with Signet of the Ether > 5 > 9 is your most important skill sequence.  Repeat this as soon as Signet is off-cooldown, and delay your 5 & 9 skills if Signet will soon be available.  Never delay this for other skills.",
            "Use 5 and 9 once each between repeats of step 1.",
            "Fill the rest of the time between repeats of step 1 with 3, 2, 7, 8, and 0 in that order of priority.",
            "Use your F1 Shatter only when you have 3 clones available."
        ]
},
    { id: 8, role:"DPS", dmgType: "Power", boon: "none",  class:"Mesmer", spec:"Virtuoso", recExpansions:["EoD"],
        notes: ["You need at least 60% base crit chance (you will get +40% from fury)."],
        exoticGearLink:"http://en.gw2skills.net/editor/?PiwAEhzlVwWZbMNmLOyKdxdA-DyQUhoGvD7Q4CHhUoCVgMPLQDFmBAA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PiwAEhzlVwUYTsNmLOyKdxdA-DyQYhomzfHUwZEhUoCVgMPLQDFmBAVA-e",
        buildTemplate:"[&DQcKGQEdQjsjDwAAggEAAGkBAACPAQAA5RoAAAAAAAAAAAAAAAAAAAAAAAA=]",
        primaryWeapons:["Greatsword"],
        secondaryWeapons:["Dagger", "Sword"],
        runes:"Dragonhunter",
        sigils:["Force", "Impact"],
        relic:"Thief",
        dpsReportLink:"https://dps.report/WwDd-20240302-144626_golem",
        instructions:["Prioritize your phantasms (GS4 + Sword 5 + Phantasmal Disenchanter)",
            "Use F skills when you have 5 blades",
            "Use your weapon phantasms before and after each weapon swap.",
            "Use your heal to reset the cooldown on greatsword 4: greatsword 4 -> heal skill -> greatsword 4.",
            "Use 1 charge of mantra of pain off cooldown"
        ]
},
    { id: 9, role:"DPS", dmgType: "Power", boon: "none",  class:"Necromancer", spec:"Reaper", recExpansions:["HoT"],
        notes: ["You need at least 75% base crit chance (you will get +25% from fury)."],
        exoticGearLink:"http://gw2skills.net/editor/?PSQAElRUwciaHBOlC3YkOSXlNbA-DyQUhw5vjCUwpwFynOUQESgKUAy8WANUYGAA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PSQAElRUwciaHBOlC3YkOSXlNbA-DyQYhogzfHUwZEhEoCFgMvFQDFmBAA-e",
        buildTemplate:"[&DQg1KTIlIjYoD5sA8RJ2AIEAgABAAZkBlQCSAAAAAAAAAAAAAAAAAAAAAAACMgBZAAA=]",
        primaryWeapons:["Greatsword"],
        secondaryWeapons:[],
        runes:"Dragonhunter",
        sigils:["Force", "Accuracy"],
        relic:"Fireworks",
        dpsReportLink:"",
        instructions:["Use Greatsword 4, 5 and then your utilities ['You Are All Weaklings!'][Well of Suffering][Well of Darkness] before entering shroud.",
            "While in Shroud use 3 and 4 right away.",
            "Auto attack until shroud 4 has 15s left and use Shoud 5",
            "Leave Shroud when Shroud 4 has 10s left on it.",
            "While in Greatsword use Greatsword 2 twice, With Greatsword 3 and an auto attack chain in between them before going back to step 1."
        ]
},
    { id: 10, role:"DPS", dmgType: "Power", boon: "none",  class:"Ranger", spec:"Soulbeast", recExpansions:["PoF"],
        notes: ["You need at least 45% base crit chance (you will get +40% from fury, +15% from flanking the target from Hunter’s Tactics)"],
        exoticGearLink:"http://gw2skills.net/editor/?POgAwelZkxu6agBut2mZmWyX+P9T+2OeB-DSIUR0wfIchrVCUhCQm3CohCzAAA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?POgAwelZkxu6agBut2mZmWyX+P9T+2OeB-DSIYR0wfG1KBqQBIzbB0QhZAAA-e",
        buildTemplate:"[&DQQeOSA+Nzp5AHkAtQC1AKUBpQGsAawBLhYuFhEXLQAAAAAAAAAAAAAAAAADWgAFACMAAA==]",
        primaryWeapons:["Sword", "Axe"],
        secondaryWeapons:[],
        runes:"Dragonhunter",
        sigils:["Force", "Impact"],
        relic:"Fireworks",
        dpsReportLink:"",
        instructions:["Stay Merged with your pet. Ideally Red Moa.",
            "Use  [Frost Trap] ['Sic 'Em!'] and [Whirling Defense] when all 3 are off cooldown together. Add [One Wolf Pack] to this where possible.",
            "Use weapon skills 2,3 and 4 off cooldown.",
            "Use F2 and F3 where available.",
            "In most situations its left to right with the utilities, F2 or F3, the left to right with the weapon skills."
        ]
},
    { id: 11, role:"DPS", dmgType: "Power", boon: "none",  class:"Revenant", spec:"Vindicator", recExpansions:["EoD"],
        notes: ["You need at least 50% base crit chance (you will get +25% from fury, and +25% from Roiling Mists)",
            "Staff is an optional weapon for more CC"
        ],
        exoticGearLink:"http://gw2skills.net/editor/?PmwAwyZlxQHMPyh1RNMO6hRSfMCKgJ7lasD-DyQUhoj8zfHKogDhLcbShKUBy8sANU4MCUB-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PmwAwyZlxQHMPyh1RNMO6hRSfMCKgJ7lasD-DSIYR0xfGtJFqQFIzzC0QhzIQFA-e",
        buildTemplate:"[&DQkDNg8qRR3cEQAA1BEAACsSAAAGEgAAyhEAAAIDAAArEgYS1BEAAAAAAAA=]",
        primaryWeapons:["Sword", "Sword"],
        secondaryWeapons:[],
        runes:"Dragonhunter",
        sigils:["Force", "Air"],
        relic:"Thief",
        dpsReportLink:"",
        instructions:["Swap Legends off-cooldown.",
            "When in Jalis, activate Vengeful Hammers and leave it on.",
            "When in Shiro, activate Impossible Odds and leave it on.",
            "Dodge when above 60 endurance",
            "Spam 2/4/5 off-cooldown",
            "Make sure to use/not cancel the second hit from 5 (Deathstrike)"
        ]
},
    { id: 12, role:"DPS", dmgType: "Power", boon: "none",  class:"Thief", spec:"Daredevil", recExpansions:["HoT"],
        notes: ["If using the exotic gear set, use Force and Accuracy Sigils instead"],
        exoticGearLink:"http://gw2skills.net/editor/?PaQAYlFwmYNMM2JO6XbtdA-DSIURUwXGRkAVUA2eWgGKcGBqA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PaQAYlFwmYNMM2JO6XbtdA-DSIYRUwXG1mAVUA2eWgGKcGBqA-e",
        buildTemplate:"[&DQUcPSMbBzsMAQAAVAEAALASAAAzAQAADgEAAAAAAAAAAAAAAAAAAAAAAAACWQBrAAA=]",
        primaryWeapons:["Staff"],
        secondaryWeapons:[],
        runes:"Scholar",
        sigils:["Force", "Impact"],
        relic:"Thief",
        dpsReportLink:"",
        instructions:["Dodge off-cooldown to keep your endurance drained.  Landing near the boss will deal bonus damage.",
            "Use Assassin’s Signet off-cooldown, then immediately spend all initiative on 2 (Weakening Charge).",
            "Use 8 (Fist Flurry) once your initiative has all been spent.",
            "Use 7 (Prepare Pitfall) off-cooldown, then trigger it while using 2 (Weakening Charge)."
        ]
},
    { id: 13, role:"DPS", dmgType: "Power", boon: "none",  class:"Thief", spec:"Deadeye", recExpansions:["PoF"],
        notes: ["If using the exotic gear set, use Force and Accuracy Sigils instead"],
        exoticGearLink:"http://gw2skills.net/editor/?PagAgilVwiYSMM2IO6LbvWA-DSIUR0wXGRkAVUA2+HgGKcGBqA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PagAgilVwiYSMM2IO6LbvWA-DSIYR0wXG1mAVUA2+HgGKcGBqA-e",
        buildTemplate:"[&DQUcPSMbOi3xFQAArBYAACAXAAAzAQAAKAAAAAAAAAAAAAAAAAAAAAAAAAACLwBVAAA=]",
        primaryWeapons:["Dagger", "Dagger"],
        secondaryWeapons:[],
        runes:"Scholar",
        sigils:["Force", "Impact"],
        relic:"Deadeye",
        dpsReportLink:"https://dps.report/iYRU-20240316-235037_golem",
        instructions:["Use Deadeye’s Mark off-cooldown to mark your target.",
            "When the Revealed debuff disappears from your bar, use Dagger 5 and then a single (ambush) auto-attack.",
            "Use either 7, 8, or your heal skill to apply the buff from Relic of the Deadeye.  When this buff goes away (it lasts for 8 seconds) use one of these skills to re-apply it.  Try to keep this buff up as close to 100% as possible.",
            "Use Thieves Guild when available for free passive damage.",
            "Fill with auto-attacks.  Do not spend initiative on any other dagger skills."
        ]
},
    { id: 14, role:"DPS", dmgType: "Power", boon: "none",  class:"Warrior", spec:"Berserker", recExpansions:["HoT"],
        notes: ["You need at least 60% base crit chance (you will get +25% from fury and +15% while in berserk mode from Smash Brawler)"],
        exoticGearLink:"http://gw2skills.net/editor/?PKgAcelRwWYTMKmJO+WatKA-DSIUR0wfIchbTCUhCQmnFohCzAAA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PKgAcelRwWYTMKmJO+WatKA-DSIYR0wfGtJBqQBIzzC0QhZAAA-e",
        buildTemplate:"[&DQIEHzMaEhXyEgAA1xIAAKkAAACvAAAAwhIAAAAAAAAAAAAAAAAAAAAAAAA=]",
        primaryWeapons:["Axe", "Axe"],
        secondaryWeapons:[],
        runes:"Dragonhunter",
        sigils:["Force", "Impact"],
        relic:"Thief",
        dpsReportLink:"https://dps.report/FsNy-20240308-235954_golem",
        instructions:["Use [Head Butt] and then [Outrage] to fill your Adrenaline and Use F2 to enter Berserk Mode.",
            "Use F1 As often as possible.",
            "Use [Blood Reckoning][Outrage][Head Butt] regularly to extend berserk mode",
            "Use weapon skills to fill gaps making sure to use one regularly to extend the thief relic duration."
        ]
},
    { id: 15, role:"DPS", dmgType: "Power", boon: "none",  class:"Warrior", spec:"Spellbreaker", recExpansions:["PoF"],
        notes: ["You will need at least 75% base crit chance (you will get +25% from fury).",
            "As you get more used to the build, you can lower your base crit chance to 63%, as you do get more precision from Attacker’s Insight."
        ],
        exoticGearLink:"http://gw2skills.net/editor/?PKgAgelFUwOScUNtpoGZnO+S1veA-DyQUhQ75vjGiogShLynOKIiEoiCw2zC0QhZAAA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PKgAgelFUwOScUNtpoGZnO+S1veA-DyQYhoh2zfHiogyIiEoiCw2zC0QhZAAA-e",
        buildTemplate:"[&DQIEHws1PT2mAKYAogGyAK8AqQCpAK8A7gCdFgAAAAAAAAAAAAAAAAAAAAACLwAFAAA=]",
        primaryWeapons:["Dagger", "Axe"],
        secondaryWeapons:[],
        runes:"Scholar",
        sigils:["Force", "Accuracy"],
        relic:"Thief",
        dpsReportLink:"https://dps.report/EnGO-20240302-173846_golem",
        instructions:["Start with your heal to generate Adrenaline",
            "Use Dagger 3 and Kick off cooldown to gain charges of Attacker's Insight",
            "Use your F1, 5 and 4 off cooldown"
        ]
},
    { id: 16, role:"DPS", dmgType: "Condition", boon: "none",  class:"Elementalist", spec:"Tempest", recExpansions:["HoT"],
        notes: ["If using the exotic gear set, use Malice and Smoldering Sigils instead"],
        exoticGearLink:"http://gw2skills.net/editor/?PGgAs2lZwuYasKGJOqOmtLA-DSRUfBFaGNcenRCKgQkAK8YANp4sCUB-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PGgAs2lZwuYasKGJOqOmtLA-DSJYmRD/ZkgCIOJgCPGQTKOrAVA-e",
        buildTemplate:"[&DQYfFRomMBd0AAAAywAAAJEAAAByAAAAJgAAAAAAAAAAAAAAAAAAAAAAAAA=]",
        primaryWeapons:["Scepter", "Focus"],
        secondaryWeapons:[],
        runes:"Trapper",
        sigils:["Smoldering", "Earth"],
        relic:"Fractal",
        dpsReportLink:"https://dps.report/k9dh-20240131-000157_golem",
        instructions:["Stay in Fire Attunement",
            "Overload Fire off-cooldown",
            "Use all weapon/utility skills off-cooldown",
            "Your Elite’s attack (Flame Barrage) is instant-cast and is the only ability that will not interrupt Overload!"
        ]
}, 
    { id: 17, role:"DPS", dmgType: "Condition", boon: "none",  class:"Engineer", spec:"Mechanist", recExpansions:["EoD"],
        notes: [],
        exoticGearLink:"http://gw2skills.net/editor/?PegAoqlxySYwMXWMOuL5xKA-DSJUmRD/hgKOOJQHKAFeMgmUcWBA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PegAoqlxySYwMXWMOuL5xKA-DSJYmRD/ZEnEoDFgCPGQTKOrAA-e",
        buildTemplate:"[&DQMGNyY5RhUNGwAAIgEAAA4bAAAQGwAACRsAAAAAAAAAAAAAAAAAAAAAAAA=]",
        primaryWeapons:["Pistol", "Pistol"],
        secondaryWeapons:[],
        runes:"Trapper",
        sigils:["Bursting", "Earth"],
        relic:"Fractal",
        dpsReportLink:"https://dps.report/fope-20240308-201748_golem",
        instructions:["Keep the Flame turret out as much as possible.",
            "Use your elite and F skills off cooldown.",
            "Use skills 2, 3 and 4 off cooldown.",
            "DO NOT activate Superconducting Signet.  Doing so is a DPS loss."
        ]
}, 
    { id: 18, role:"DPS", dmgType: "Condition", boon: "none",  class:"Guardian", spec:"Firebrand", recExpansions:["PoF"],
        notes: ["If using the exotic gear set, use Malice and Smoldering Sigils instead",
            "DPS will be higher in a group because of Ashes of the Just."
        ],
        exoticGearLink:"http://gw2skills.net/editor/?PWgAc+lVwgYdsKmJW0WfvSA-DSRUfhIC0Mao9+OjEkAhoAU4xAaSxZFoC-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PWgAc+lVwgYdsKmJW0WfvSA-DSJYmRD/ZkgEoDFgCPGQTKOrAVA-e",
        buildTemplate:"[&DQEQGi4fPiUmDwAAFRcAAEwBAAAxAQAAGBYAAAAAAAAAAAAAAAAAAAAAAAADBQBmAFYAAA==]",
        primaryWeapons:["Axe", "Torch"],
        secondaryWeapons:[],
        runes:"Trapper",
        sigils:["Bursting", "Smoldering"],
        relic:"Fractal",
        dpsReportLink:"https://dps.report/Dj3E-20240316-225153_golem",
        instructions:["Use both sides of your 4 skill (Zealot’s Flame/Zealot’s Fire] back-to-back off-cooldown.",
            "When your 4 skill goes on cooldown, enter Tome 1.",
            "In Tome 1 use 5 > 2 > 4, and then exit Tome 1.  All 3 will not be available every time you enter the Tome, so cast the one(s) available and then exit.  Do not wait for skills in Tome 1 to come off of cooldown.",
            "Use Mantra of Flame and all of its charges.",
            "Use 2, 3, and 8 off-cooldown."
        ]
}, 
    { id: 19, role:"DPS", dmgType: "Condition", boon: "none",  class:"Guardian", spec:"Willbender", recExpansions:["EoD", "SotO"],
        notes: [],
        exoticGearLink:"http://gw2skills.net/editor/?PWgAo+lVw6YqsKWLW0WXxSA-DSRUfBdYGNc4jR7CoTC44YAL8eWBVA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PWgAo+lVw6YqsKWLW0WXxSA-DSRYfB1bGNcCnRbKgOkAK8YAL8eWBVA-e",
        buildTemplate:"[&DQEQGi4XQSUmDwAATAEAANgaAAAxAQAA6RoAAAAAAAAAAAAAAAAAAAAAAAA=]",
        primaryWeapons:["Pistol", "Torch"],
        secondaryWeapons:[],
        runes:"Balthazar",
        sigils:["Bursting", "Air"],
        relic:"Fractal",
        dpsReportLink:"",
        instructions:["Use F1 off-cooldown.",
            "Torch 4 is your highest priority skill; use it off-cooldown.  It is also instant-cast and will not interrupt other skills.",
            "Use Purging Flames and Whirling Light off-cooldown.",
            "Using your Virtues gives you a damage bonus.  While F2 is forced movement, F1 or F3 can be used directly after to put you right back on the boss.  Try to always follow F2 with either F1 or F3.",
            "Use your other weapon skills with the following priority 3 > 2 > 5."
        ]
}, 
    { id: 20, role:"DPS", dmgType: "Condition", boon: "none",  class:"Mesmer", spec:"Mirage", recExpansions:["PoF"],
        notes: [],
        exoticGearLink:"http://gw2skills.net/editor/?PigAcrlRwiYIsEmJWKP1vOA-DSJUmRJ/ZkpQIXFgCPGQTKOrAVA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PigAcrlRwiYIsEmJWKP1vOA-DSJYmRJ/ZkpQIXFgCPGQTKOrAVA-e",
        buildTemplate:"[&DQctPQElOx3uFQAA4BUAAIMBAACBAQAARhcAAAAAAAAAAAAAAAAAAAAAAAACBQA2AAA=]",
        primaryWeapons:["Axe", "None"],
        secondaryWeapons:["None", "Pistol"],
        runes:"Trapper",
        sigils:["Torment", "Energy"],
        relic:"Fractal",
        dpsReportLink:"",
        instructions:["A large portion of this build’s damage comes from your Axe ambush skill (from both you and your clones).  Generating Mirage Cloak and immediately following it with the Axe ambush attack is essential to doing good damage with the build.",
            "Begin combat by using 4 > 2 to generate 2 clones",
            "6 & 7 generate Mirage Mirrors.  Picking up these mirrors will trigger Mirage Cloak. Dodging will trigger Mirage Cloak.  Do this as often as possible, immediately following Mirage Cloak with your Axe ambush skill (and letting it complete!).",
            "Swapping weapons will restore 50% of your energy, allowing you to dodge more frequently.  Be sure to do this when below 50% energy so that it is not wasted.",
            "Use 3, 4, and 5 off-cooldown, but delay them in favor of Cloak > Ambush if it is available."
        ]
}, 
    { id: 21, role:"DPS", dmgType: "Condition", boon: "none",  class:"Mesmer", spec:"Virtuoso", recExpansions:["EoD"],
        notes: ["You need at least 60% base crit chance (you will get +40% from fury). This is critical for this spec to work."],
        exoticGearLink:"http://gw2skills.net/editor/?PiABgyh3lVwWZJMEmLW6WdxdA-DSRUmRPUE+BBNHPF6UB+eBQTKOrAVA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PiABgyh3lVwWZJMEmLW6WdxdA-DSZYfhCYG9EhiQ6PGxThOVgvXA0kizKQFA-e",
        buildTemplate:"[&DQcBHRgdQjsjDwAA3RoAAIMBAACBAQAA5RoAAAAAAAAAAAAAAAAAAAAAAAA=]",
        primaryWeapons:["Dagger", "Sword"],
        secondaryWeapons:["None", "Focus"],
        runes:"Krait",
        sigils:["Earth", "Bursting"],
        relic:"Aristocracy",
        dpsReportLink:"https://dps.report/4DIx-20240302-154311_golem",
        instructions:["Press all weapon skills aside from the 4.",
            "Use Shatters when Blades are full.",
            "Make sure you have cast your phantasm (5 skill) twice in each set before you weapon swap.",
            "Use your heal to remove the cooldown for your phantasms(5 skill) on focus to be able to cast it"
        ]
}, 
    { id: 22, role:"DPS", dmgType: "Condition", boon: "none",  class:"Necromancer", spec:"Harbinger", recExpansions:["EoD", "SotO"],
        notes: [],
        exoticGearLink:"http://gw2skills.net/editor/?PSgAo+lhG6ADcpxuqSXbkWsX1xfA-DSJUmRD/hgKOXFQISAFeMgGZcWBqA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PSgAo+lhG6ADcpxuqSXbkWsX1xfA-DSRYfBBaGNcfnRuKgQkAK8YANy4sCUB-e",
        buildTemplate:"[&DQgnNjI1QD/nGucagACAAOwa1BpwAewa6BqSAAAAAAAAAAAAAAAAAAAAAAA=]",
        primaryWeapons:["Pistol", "Torch"],
        secondaryWeapons:[],
        runes:"Trapper",
        sigils:["Torment", "Bursting"],
        relic:"Fractal",
        dpsReportLink:"https://dps.report/4Lvj-20240308-194958_golem",
        instructions:["Use All Weapon Skills off Cooldown",
            "Use all utilities off cooldown aside from [Blood Is Power]",
            "Use [Blood Is Power] prior to going into shroud",
            "Go into shroud after using Pistol 2 3x.",
            "Leave shroud after using Shroud 2 3x."
        ]
}, 
    { id: 23, role:"DPS", dmgType: "Condition", boon: "none",  class:"Necromancer", spec:"Scourge", recExpansions:["PoF", "SotO"],
        notes: [],
        exoticGearLink:"http://gw2skills.net/editor/?PSgAo+lRUxAZXMNGJWsX1PVA-DSJUmRD/hgKOXFQHSAFeMgGZcDAqA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PSgAo+lRUxAZXMNGJWsX1PVA-DSJYmRD/ZkrCoDJgCPGQjMuBAVA-e",
        buildTemplate:"[&DQgnNjI1PCooD6IAgAAAAHUBAABvAQAAkgAAAAAAAAAAAAAAAAAAAAAAAAADNgBmAFYAAA==]",
        primaryWeapons:["Pistol", "Torch"],
        secondaryWeapons:[],
        runes:"Trapper",
        sigils:["Torment", "Bursting"],
        relic:"Fractal",
        dpsReportLink:"https://dps.report/fzyu-20240308-191219_golem",
        instructions:["ress F2 Every time it is off cooldown regardless of what else is going on.",
            "Cast F1 regularly to keep at least 1 shade out at a time.",
            "Use [Blood Is Power] in combination with your F5 shade to instantly transfer the conditions.",
            "Cast all weapon skills, [Signet of Spite] & [Plaguelands] off cooldown."
        ]
}, 
    { id: 24, role:"DPS", dmgType: "Condition", boon: "none",  class:"Ranger", spec:"Druid", recExpansions:["HoT", "SotO"],
        notes: ["Pet: Jacaranda"],
        exoticGearLink:"http://gw2skills.net/editor/?POgAg+lZwoYfsN2JW6P3t/RMH-DSJUmRD/ZUgCIOJgCPGQTKOrAVA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?POgAg+lZwoYfsN2JW6P3t/RMH-DSJYmRD/ZUgCIOJgCPGQTKOrAVA-e",
        buildTemplate:"[&DQQePSE3BT95AHkAGwC9AL8AuQCsAcIAwACXAS05AAAAAAAAAAAAAAAAAAADLwBmAGsAAA==]",
        primaryWeapons:["Dagger", "Torch"],
        secondaryWeapons:[],
        runes:"Trapper",
        sigils:["Agony", "Earth"],
        relic:"Fractal",
        dpsReportLink:"https://dps.report/B3jK-20240316-220502_golem",
        instructions:["Enter Celestial Avatar (F5) off-cooldown.",
            "While in Celestial Avatar, use 5 > 2 > 3.  As soon as 3 completes casting, exit Celestial Avatar.",
            "Use all weapon, utility, elite, and beast skills off-cooldown."
        ]
}, 
    { id: 25, role:"DPS", dmgType: "Condition", boon: "none",  class:"Thief", spec:"Specter", recExpansions:["EoD"],
        notes: ["Scepter in one set, dagger in the other set."],
        exoticGearLink:"http://gw2skills.net/editor/?PaABsitjlhy8YHME2JO2WXxKA-DSJUmRP/hgKOSpQuqAFeMgGZcWBqA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PaABsitjlhy8YHME2JO2WfxKA-DSJYmRP/ZEpUIXVgCPGQjMOrAVA-e",
        buildTemplate:"[&DQUcGywfRxUVGwAAWwEAAC8BAAA+AQAADgEAAAAAAAAAAAAAAAAAAAAAAAA=]",
        primaryWeapons:["Scepter", "Dagger"],
        secondaryWeapons:[],
        runes:"Trapper",
        sigils:["Torment", "Doom"],
        relic:"Fractal",
        dpsReportLink:"https://dps.report/LVHV-20240301-022312_golem",
        instructions:["Use Scepter 3 and your Trap and Venoms when out of shroud.",
            "Use Shroud regularly (when out of initiative)",
            "Use 2 & 4 in shroud, casting 2 three times before leaving shroud.",
            "Use Siphon off-cooldown to restore initiative to be able to keep casting Scepter 3."
        ]
},
    { id: 26, role: "BoonDPS", dmgType: "Condition", boon: "Alacrity", class:"Engineer", spec:"Mechanist", recExpansions:["EoD"],
        notes: ["Exotic buils is same as ascended build, just be aware crafting Ritualist gear is quite expensive. Consider making ascended gear instead, if possible."],
        exoticGearLink:"",
        ascendedGearLink:"http://gw2skills.net/editor/?PegAoqlxyaZwMXWMOOLpRVA-DSJYyRD/ZEnEoDFgCPGQjMOrAVA-e",
        buildTemplate:"[&DQMGJyYpRioNGwAACxsAAA4bAAAQGwAACRsAAAAAAAAAAAAAAAAAAAAAAAABNgAA]",
        primaryWeapons:["Pistol", "Pistol"],
        secondaryWeapons:[],
        runes:"Trapper",
        sigils:["Bursting", "Earth"],
        relic:"Fractal",
        dpsReportLink:"https://dps.report/p7yH-20240308-205842_golem",
        instructions:["Use your [Barrier Signet] and F2, F3 skills off cooldown for Alacrity",
            "Use your Elite, F1 and weapon skills 2, 3 and 4 off cooldown."
        ]
}, 
    { id: 27, role: "BoonDPS", dmgType: "Power", boon: "Alacrity", class:"Engineer", spec:"Mechanist", recExpansions:["EoD", "SotO"],
        notes: [],
        exoticGearLink:"http://gw2skills.net/editor/?PeQAIlxWwarauZt3uWcqOuLvRVA-DSJUwRB/ZUrEoCFgMvFQDFmBAVA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PeQAIlxWwarauZt3uWcqOuLvRVA-DSJYwRB/ZUrEoCFgMvFQDFmBAVA-e",
        buildTemplate:"[&DQMmLwY3RioNGxQBCxsBARAbXwEaG14BCRsSAQAAAAAAAAAAAAAAAAAAAAADMwA1AFcAAA==]",
        primaryWeapons:["Hammer"],
        secondaryWeapons:[],
        runes:"Dragonhunter",
        sigils:["Force", "Impact"],
        relic:"Fireworks",
        dpsReportLink:"",
        instructions:["Use your [Barrier Signet] and F2, F3 skills off cooldown for Alacrity",
            "Use your Elite, F1 and weapon skills 2, 3 and 5 off cooldown."
        ]
}, 
    { id: 28, role: "BoonDPS", dmgType: "Power", boon: "Alacrity", class:"Mesmer", spec:"Chronomancer", recExpansions:["HoT", "SotO"],
        notes: ["You need at least 75% base crit chance (you will get +25% from fury)",
            "This build will give you 100% boon duration with these instructions.",
            "If you are having trouble keeping 100% boon uptime, do NOT change gear or utility.",
            "You can change Sigil of Impact for Sigil of Concentration, or take concentration food instead of power food."
        ],
        exoticGearLink:"http://gw2skills.net/editor/?PiwAgyFlVwYYLsNWJOyKdNPA-DyQUhgC2RHn/YEJFqUBSPLQDFetAVA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PiwAgyFlVwYYLsNWJOyKdNPA-DyQYhoDRuD3WZUbKURFI1ZBaowrFoC-e",
        buildTemplate:"[&DQcKGQEdKB4jDwAABBMAAM8SAACPAQAAsxIAAAAAAAAAAAAAAAAAAAAAAAA=]",
        primaryWeapons:["Dagger", "Sword"],
        secondaryWeapons:["Greatsword"],
        runes:"Infiltration",
        sigils:["Force", "Impact"],
        relic:"Thief",
        dpsReportLink:"https://dps.report/sWga-20240308-232205_golem",
        instructions:["Press sword 5 twice before swapping weapons",
            "Press greatsword 4 twice before swapping weapons",
            "Every time you press greatsword 4, if heal skill is available, use greatsword 4 -> heal signet -> greatsword 4",
            "Shatter (F1/F2) every time you have 3 clones available",
            "When not doing any of the steps above, sprinkle in weapon 3 -> 2 skills + wells"
        ]
}, 
    { id: 29, role: "BoonDPS", dmgType: "Condition", boon: "Alacrity", class:"Necromancer", spec:"Scourge", recExpansions:["PoF", "SotO"],
        notes: ["Exotic buils is same as ascended build, just be aware crafting Ritualist gear is quite expensive. Consider making ascended gear instead, if possible."],
        exoticGearLink:"",
        ascendedGearLink:"http://gw2skills.net/editor/?PSgAo+lNkxADcSVNt0GZkWsX1PfA-DSJYyRD/ZkrCoDJgCPGQjMuBAA-e",
        buildTemplate:"[&DQgnNjI1PD5+FhIAgACAACEXcAFvAW8BkgCSAAAAAAAAAAAAAAAAAAAAAAADNgBmAFYAAA==]",
        primaryWeapons:["Pistol", "Torch"],
        secondaryWeapons:[],
        runes:"Trapper",
        sigils:["Malice", "Torment"],
        relic:"Fractal",
        dpsReportLink:"",
        instructions:["Use F3[Sand Cascade], F5[Sandstorm Shroud] and [Serpent Siphon] off cooldown",
            "Use Blood is power  before using F5[Sandstorm Shroud].",
            "Use all weapon skills (2,3,4,5) and your elite [Plaguelands] off cooldown."
        ]
},
    { id: 30, role: "BoonDPS", dmgType: "Condition", boon: "Quickness", class:"Guardian", spec:"Firebrand", recExpansions:["PoF", "SotO"],
        notes: ["Exotic buils is same as ascended build, just be aware crafting Ritualist gear is quite expensive. Consider making ascended gear instead, if possible.",
            "You need at least 50% base crit chance (you will get +25% from fury, and +25% from Roiling Mists)",
            "If you need to bring different utilities for a fight, replace Mantra of Flame and Purging Flames, but not any other utilities."
        ],
        exoticGearLink:"",
        ascendedGearLink:"http://gw2skills.net/editor/?PWgAo+lRweYQsOGJW0WbPTA-DSJYyRD/ZkgCoDJgYPGQzO+0AVA-e",
        buildTemplate:"[&DQEQGi4bPiZLFwAAehYAABUXAABMAQAAiRIAAAAAAAAAAAAAAAAAAAAAAAA=]",
        primaryWeapons:["Pistol", "Torch"],
        secondaryWeapons:[],
        runes:"Firebrand",
        sigils:["Smoldering", "Bursting"],
        relic:"Fractal",
        dpsReportLink:"",
        instructions:["Use off cooldown, in this order of priority: Torch 4, Pistol 3, Pistol 2.",
            "Use all utilities off cooldown, spend all charges of the mantras, except for healing mantra",
            "Use 1 charge of the healing mantra, every time it reaches 3 charges, use it again.",
            "Torch 4 and Mantras are instant casts, they won’t interrupt any other skills. Use them while casting other skills."
        ]
}, 
    { id: 31, role: "BoonDPS", dmgType: "Power", boon: "Quickness", class:"Mesmer", spec:"Chronomancer", recExpansions:["HoT", "SotO"],
        notes: ["You need at least 75% base crit chance (you will get +25% from fury)",
            "This build will give you 100% boon duration with these instructions.",
            "If you are having trouble keeping 100% boon uptime, do NOT change gear or utility.",
            "You can change Sigil of Impact for Sigil of Concentration, or take concentration food instead of power food."
        ],
        exoticGearLink:"http://gw2skills.net/editor/?PiwAgyFlVwYYLsNWJOyKdNXA-DyQUhgC2RHn/YEJFqUBSPLQDFetAVA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PiwAgyFlVwYYLsNWJOyKdNXA-DyQYhoDRuD3WZUbKURFI1ZBaowrFoC-e",
        buildTemplate:"[&DQcKGQEdKC4jDwAABBMAAM8SAACPAQAAsxIAAAAAAAAAAAAAAAAAAAAAAAA=]",
        primaryWeapons:["Dagger", "Sword"],
        secondaryWeapons:["Greatsword"],
        runes:"Infiltration",
        sigils:["Force", "Impact"],
        relic:"Thief",
        dpsReportLink:"https://dps.report/n7Ik-20240308-233751_golem",
        instructions:["Press sword 5 twice before swapping weapons",
            "Press greatsword 4 twice before swapping weapons",
            "Every time you press greatsword 4, if heal skill is available, use greatsword 4 -> heal signet -> greatsword 4",
            "Shatter (F1/F2) every time you have 3 clones available",
            "When not doing any of the steps above, sprinkle in weapon 3 -> 2 skills + wells"
        ]
}, 
    { id: 32, role: "BoonDPS", dmgType: "Condition", boon: "Quickness", class:"Necromancer", spec:"Harbinger", recExpansions:["EoD", "SotO"],
        notes: [],
        exoticGearLink:"http://gw2skills.net/editor/?PSgAo+lhG6ALZpluqYXbkWsX1xVA-DSJUmRD/hgKOXFQISAFeMgGZcWBA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PSgAo+lhG6ALZpluqYXbkWsX1xVA-DSJYmRD/ZkrCIEJgCPGQjMuBAVA-e",
        buildTemplate:"[&DQgnNjI1QCvnGucagAB0Aewa7BpwAdQa6BqSAAAAAAAAAAAAAAAAAAAAAAA=]",
        primaryWeapons:["Pistol", "Torch"],
        secondaryWeapons:[],
        runes:"Trapper",
        sigils:["Malice", "Torment"],
        relic:"Fractal",
        dpsReportLink:"",
        instructions:["Use potions on both yourself and the enemy. Using the Healing potion and Elite Potion as the last two.", 
            "Use Blood is Power before going into shroud.",
            "Use the Shroud 2, 3 and 4 off cooldown both in and outside of shroud.",
            "Use Shroud off Cooldown."
        ]
}, 
    { id: 33, role: "BoonDPS", dmgType: "Power", boon: "Quickness", class:"Revenant", spec:"Herald", recExpansions:["HoT", "SotO"],
        notes: ["You need at least 50% base crit chance (you will get +25% from fury, and +25% from Roiling Mists)"],
        exoticGearLink:"http://gw2skills.net/editor/?PmQAElxQKMPyi1RXMOCjRSiMCqgJ7lezC-DyQUhog8zfHKogDhLctSgKUAy8sANUYGAA-e",
        ascendedGearLink:"http://gw2skills.net/editor/?PmQAElxQKMPyi1RXMOCjRSiMCqgJ7lezC-DSIYRUwfG1KBqQBIzzC0QhZAAA-e",
        buildTemplate:"[&DQkDNg86NBbcEQAA1BEAACsSAAAGEgAAyhEAAAIBAAAGEisS1BEAAAAAAAA=]",
        primaryWeapons:["Greatsword"],
        secondaryWeapons:[],
        runes:"Dragonhunter",
        sigils:["Force", "Impact"],
        relic:"Thief",
        dpsReportLink:"",
        instructions:["In Glint, Activate the F2, [Facet of Strength] and [Facet of Chaos]",
            "In Glint, Activate and then immediately consume [Facet of Darkness] and [Facet of Elements]",
            "In Shiro Activate [Impossible Odds]",
            "Switch Legends when your energy gets low.",
            "Use 2, 3 and 5 off cooldown."
        ]
}
]